version: 1
disable_existing_loggers: False


formatters:
    standard:
        format: '%(asctime)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s'


handlers:
    console:
        level: INFO
        class: logging.StreamHandler
        stream: ext://sys.stdout
    graylog:
        level: DEBUG
        class: graypy.GELFUDPHandler
        host: 10.0.100.5
        port: 12202

root:
    level: DEBUG
    handlers: [console, graylog]

loggers:
    logger:
        level: DEBUG
        handlers: [console, graylog]
        propagate: no